NAME = Sed

CXX = g++

CPPFLAGS = -Wall -Wextra -Werror -std=c++98 -fsanitize=address

FILES = main.cpp class.cpp

OBJECTS = $(FILES:.cpp=.o)
OBJECTS = $(FILES:.cpp=.o)

all : $(NAME)

$(NAME) : $(OBJECTS)
$(NAME) : $(OBJECTS)
		$(CXX) $(CPPFLAGS) $(OBJECTS) -o $(NAME)
		$(CXX) $(CPPFLAGS) $(OBJECTS) -o $(NAME)

clean :
	rm -fr $(OBJECTS)
	rm -fr $(OBJECTS)

fclean :clean
	rm -fr $(NAME)

re : fclean all

.PHONY :  all re clean fclean 
