NAME = Acount

CXX = c++ -std=c++98

CPPFLAGS = Wall -Wextra -Werror

FILES = Acount.cpp

OBJCS = $(NAME:.cpp=.o)

all : $(NAME)

$(NAME) : $(OBJCS)
	$(CXX) $(CPPFLAGS) $(OPBJCS) -o $(NAME)
clean : 
	rm -fr $(OBJCS)

fclean : clean
	rm -fr $(NAME)

re : fclean all



